# Generated by Django 3.2.13 on 2022-06-21 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0002_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationEpidemicSituation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('areas', models.CharField(max_length=256, verbose_name='区域ID集合')),
                ('level', models.IntegerField(choices=[(1, '中风险地区'), (2, '高风险地区')], verbose_name='风险地区类型')),
                ('desc', models.TextField(verbose_name='风险地区描述')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin.city', verbose_name='城市ID')),
                ('province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin.province', verbose_name='省份ID')),
            ],
        ),
    ]
