# Generated by Django 3.2.13 on 2022-06-22 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_locationepidemicsituation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationepidemicsituation',
            name='areas',
            field=models.CharField(max_length=256, verbose_name='区域集合'),
        ),
        migrations.AlterField(
            model_name='locationepidemicsituation',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin.city', verbose_name='城市'),
        ),
        migrations.AlterField(
            model_name='locationepidemicsituation',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin.province', verbose_name='省份'),
        ),
    ]
