# Generated by Django 3.2.13 on 2022-06-22 15:59

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0004_auto_20220622_2351'),
    ]

    operations = [
        migrations.CreateModel(
            name='VaccineCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='疫苗公司')),
            ],
        ),
        migrations.CreateModel(
            name='VaccineLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='接种单位')),
            ],
        ),
        migrations.CreateModel(
            name='Vaccines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('needles', models.IntegerField(choices=[(1, '第一针'), (2, '第二针'), (3, '第三针')], verbose_name='针次')),
                ('quantity', models.IntegerField(verbose_name='数量')),
                ('create_time', models.DateTimeField(default=datetime.datetime(2022, 6, 22, 15, 59, 3, 87940, tzinfo=utc), verbose_name='发布时间')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin.vaccinecompany', verbose_name='接种单位')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin.vaccinelocation', verbose_name='疫苗公司')),
            ],
        ),
    ]
