# Generated by Django 3.2.13 on 2022-06-23 04:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0006_auto_20220623_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='public_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='vaccines',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 23, 4, 12, 26, 544115, tzinfo=utc), verbose_name='发布时间'),
        ),
    ]
