# Generated by Django 3.2.13 on 2022-06-23 04:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0007_auto_20220623_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccines',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='发布时间'),
        ),
    ]
