# Generated by Django 3.2.13 on 2022-06-23 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0008_alter_vaccines_create_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin.city', verbose_name='城市ID'),
        ),
        migrations.AlterField(
            model_name='case',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin.province', verbose_name='省份(自治区)'),
        ),
        migrations.AlterField(
            model_name='city',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin.province', verbose_name='省份ID'),
        ),
        migrations.AlterField(
            model_name='locationepidemicsituation',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin.city', verbose_name='城市'),
        ),
        migrations.AlterField(
            model_name='locationepidemicsituation',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin.province', verbose_name='省份'),
        ),
        migrations.AlterField(
            model_name='vaccines',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin.vaccinecompany', verbose_name='接种单位'),
        ),
        migrations.AlterField(
            model_name='vaccines',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin.vaccinelocation', verbose_name='疫苗公司'),
        ),
    ]
