# Generated by Django 3.2.13 on 2022-06-23 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0010_areaoutpatientdepartment_areapolicy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areapolicy',
            name='epidemic_prevention_policy',
            field=models.TextField(blank=True, null=True, verbose_name='防疫政策'),
        ),
        migrations.AlterField(
            model_name='areapolicy',
            name='psychological_hotline',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='心理热线'),
        ),
        migrations.AlterField(
            model_name='areapolicy',
            name='travel_policy',
            field=models.TextField(blank=True, null=True, verbose_name='出行政策'),
        ),
    ]
