# Generated by Django 3.2.13 on 2022-06-23 16:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0013_auto_20220623_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(default=uuid.UUID('4e444cee-cd56-4c22-b67c-e44809e6280c'), max_length=128, verbose_name='昵称'),
        ),
        migrations.CreateModel(
            name='HealthReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=256, verbose_name='本人当前所在位置')),
                ('health_code_status', models.IntegerField(default=1, verbose_name='当前健康码状态')),
                ('trip_card_status', models.IntegerField(choices=[(1, '否'), (2, '是')], default=1, verbose_name='本人大数据行程卡是否带"*"')),
                ('vaccination_status', models.IntegerField(choices=[(1, '已经接种三针'), (2, '已经接种二针'), (3, '已经接种一针'), (4, '未接种')], default=1, verbose_name='接种新冠疫苗情况')),
                ('error_area', models.IntegerField(choices=[(1, '否'), (2, '是')], default=1, verbose_name='当日是否14天内到达过中高风险地区?')),
                ('is_fever', models.IntegerField(choices=[(1, '否'), (2, '是')], default=1, verbose_name='今日是否出现发热情况?(腋温≥37.3℃)')),
                ('body_status', models.IntegerField(choices=[(1, '正常'), (2, '干咳、乏力、 嗅觉味觉退减、鼻、咽痛、结膜炎、肌痛和腹泻任一症状'), (3, '其他')], default=1, verbose_name='目前身体状态')),
                ('health_observations', models.IntegerField(choices=[(1, '无需观察'), (2, '自我健康监测'), (3, '居家健康检测'), (4, '医学居家隔离'), (5, '医学集中隔离(在政府规定的酒店或医院灯场所集中健康观察)')], default=1, verbose_name='目前健康观察情况为')),
                ('public_date', models.DateField(default=django.utils.timezone.now, verbose_name='发布时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin.user', verbose_name='用户')),
            ],
        ),
    ]
