# Generated by Django 3.2.13 on 2022-06-23 16:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0014_auto_20220624_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthreport',
            name='health_code_status',
            field=models.IntegerField(choices=[(1, '绿码'), (2, '黄码'), (3, '红码')], default=1, verbose_name='当前健康码状态'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(default=uuid.UUID('0231d018-609a-4720-8431-94adbda3e11c'), max_length=128, verbose_name='昵称'),
        ),
    ]
