# Generated by Django 3.2.13 on 2022-06-24 18:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0015_auto_20220624_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(default=uuid.UUID('72a594dd-7ce6-45f5-b6fe-b622a6964207'), max_length=128, verbose_name='昵称'),
        ),
        migrations.CreateModel(
            name='UserVaccines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_of_appointment', models.DateField(default=django.utils.timezone.now, verbose_name='预约时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin.user', verbose_name='预约用户')),
                ('vaccines', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin.vaccines', verbose_name='疫苗')),
            ],
        ),
    ]
